# Generated by Django 5.0.4 on 2024-04-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='team',
            field=models.IntegerField(default=0, verbose_name='Отряд'),
            preserve_default=False,
        ),
    ]
