# Generated by Django 5.0.4 on 2024-04-19 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_teams_remove_users_auth_flag_remove_users_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='scores_team',
        ),
        migrations.RemoveField(
            model_name='users',
            name='tg_userid',
        ),
    ]
