# Generated by Django 5.0.4 on 2024-04-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_users_scores_team_remove_users_tg_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Ссылка',
            },
        ),
    ]
