# Generated by Django 5.0.4 on 2024-04-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_adminview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminView',
        ),
    ]
