# Generated by Django 5.0.4 on 2024-04-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_adminview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.IntegerField(verbose_name='Конкурс')),
                ('description', models.IntegerField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Конкурсы',
            },
        ),
    ]
