# Generated by Django 5.0.4 on 2024-04-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='contest',
            field=models.TextField(verbose_name='Конкурс'),
        ),
        migrations.AlterField(
            model_name='contests',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
