# Generated by Django 5.0.4 on 2024-04-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_contests_contest_alter_contests_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='data',
            field=models.TextField(default=0, verbose_name='Дата проведения(сроки)'),
            preserve_default=False,
        ),
    ]
